language: node_js
node_js: '12'

after_success:
  - codecov

cache: npm

stages:
  - lint
  - test

env: SUPPORTED_ESLINT_MAJORS='6 7 8'
jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint

    - &test
      stage: test
      name: test-plugin-node12
      node_js: '12'
      install:
        - npm install
        - npm run integration install $SUPPORTED_ESLINT_MAJORS
      script:
        - npm test
        - npm run integration test $SUPPORTED_ESLINT_MAJORS

    - <<: *test
      name: test-plugin-node14
      node_js: '14'

    - <<: *test
      name: test-plugin-node16
      node_js: '16'
